In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

In [44]:
current_path = os.getcwd()
data_path = os.path.join(current_path, 'manifest-MjbMt99Q1553106146386120388')
metadata_path = os.path.join(data_path, 'metadata.csv')
info_path = os.path.join(data_path, 'INFOclinical_STS_csv.csv')
# import data
metadata = pd.read_csv(metadata_path)
info = pd.read_csv(info_path)

In [9]:
info.head()

,Subject ID,MSKCC type,Site of primary STS,Grade,Time - diagnosis to MRI scan (days),Time - MRI scan to PET scan (days),Treatment,"Outcome (recurrence, mets)",Time - diagnosis to outcome (days),"Status (NED, AWD, D)",Time - diagnosis to last follow-up (days)
0,STS_001,Liposarcoma,left thigh,High,-7,4,Radiotherapy + Surgery + Chemotherapy,Mets - arms,266,D,845
1,STS_002,Leiomyosarcoma,left buttock,High,-10,25,Radiotherapy + Surgery,--,--,NED,501
2,STS_003,Other,right buttock,Intermediate,-13,15,Radiotherapy + Surgery,--,--,NED,756
3,STS_004,MFH,right thigh,Low,-6,22,Radiotherapy + Surgery,--,--,NED,1792
4,STS_005,Leiomyosarcoma,left biceps,High,-24,34,Radiotherapy + Surgery,--,--,NED,647

In [10]:
metadata.head()

,Series UID,Collection,3rd Party Analysis,Data Description URI,Subject ID,Study UID,Study Description,Study Date,Series Description,Manufacturer,Modality,SOP Class Name,SOP Class UID,Number of Images,File Size,File Location,Download Timestamp
0,1.3.6.1.4.1.14519.5.2.1.5168.1900.169505605471...,Soft-tissue-Sarcoma,NaN,https://doi.org/10.7937/K9/TCIA.2015.7GO2GSKS,STS_001,1.3.6.1.4.1.14519.5.2.1.5168.1900.288970202012...,THIGH,09-03-2000,RTstructT1,MIM Software Inc.,RTSTRUCT,RT Structure Set Storage,1.2.840.10008.5.1.4.1.1.481.3,1,1.05 MB,.\Soft-tissue-Sarcoma\STS_001\09-03-2000-NA-TH...,2022-12-04T15:17:17.081
1,1.3.6.1.4.1.14519.5.2.1.5168.1900.236909650266...,Soft-tissue-Sarcoma,NaN,https://doi.org/10.7937/K9/TCIA.2015.7GO2GSKS,STS_001,1.3.6.1.4.1.14519.5.2.1.5168.1900.288970202012...,THIGH,09-03-2000,AXIAL SE T1 - RESEARCH,SIEMENS,MR,MR Image Storage,1.2.840.10008.5.1.4.1.1.4,40,21.06 MB,.\Soft-tissue-Sarcoma\STS_001\09-03-2000-NA-TH...,2022-12-04T15:17:18.905
2,1.3.6.1.4.1.14519.5.2.1.5168.1900.269249420684...,Soft-tissue-Sarcoma,NaN,https://doi.org/10.7937/K9/TCIA.2015.7GO2GSKS,STS_001,1.3.6.1.4.1.14519.5.2.1.5168.1900.288970202012...,THIGH,09-03-2000,RTstructT2FS,MIM Software Inc.,RTSTRUCT,RT Structure Set Storage,1.2.840.10008.5.1.4.1.1.481.3,1,793.95 KB,.\Soft-tissue-Sarcoma\STS_001\09-03-2000-NA-TH...,2022-12-04T15:17:20.531
3,1.3.6.1.4.1.14519.5.2.1.5168.1900.267475167888...,Soft-tissue-Sarcoma,NaN,https://doi.org/10.7937/K9/TCIA.2015.7GO2GSKS,STS_001,1.3.6.1.4.1.14519.5.2.1.5168.1900.288970202012...,THIGH,09-03-2000,AXIAL SE T2 FAT SAT - RESEARCH,SIEMENS,MR,MR Image Storage,1.2.840.10008.5.1.4.1.1.4,40,11.89 MB,.\Soft-tissue-Sarcoma\STS_001\09-03-2000-NA-TH...,2022-12-04T15:17:22.271
4,1.3.6.1.4.1.14519.5.2.1.5168.1900.147597676388...,Soft-tissue-Sarcoma,NaN,https://doi.org/10.7937/K9/TCIA.2015.7GO2GSKS,STS_001,1.3.6.1.4.1.14519.5.2.1.5168.1900.980314374925...,PET CT,09-07-2000,RTstructAlignedT1toPET,MIM Software Inc.,RTSTRUCT,RT Structure Set Storage,1.2.840.10008.5.1.4.1.1.481.3,1,1.22 MB,.\Soft-tissue-Sarcoma\STS_001\09-07-2000-NA-PE...,2022-12-04T15:17:22.541

In [27]:
metadata[['Subject ID','Modality']]

    Subject ID  Modality
0      STS_001  RTSTRUCT
1      STS_001        MR
2      STS_001  RTSTRUCT
3      STS_001        MR
4      STS_001  RTSTRUCT
..         ...       ...
607    STS_051  RTSTRUCT
608    STS_051        CT
609    STS_051        MR
610    STS_051        MR
611    STS_051        PT

[612 rows x 2 columns]

In [24]:
metadata[['Number of Images','Modality']].groupby('Modality').sum()

          Number of Images
Modality
CT                   13607
MR                   10753
PT                   13617
RTSTRUCT               306

In [76]:

print(metadata[['Subject ID','Modality','Number of Images']]
      .groupby(['Subject ID', 'Modality'])
      .sum())

                     Number of Images
Subject ID Modality
STS_001    CT                     267
           MR                     201
           PT                     267
           RTSTRUCT                 6
STS_002    CT                     267
...                               ...
STS_050    RTSTRUCT                 6
STS_051    CT                     267
           MR                     198
           PT                     267
           RTSTRUCT                 6

[204 rows x 1 columns]

In [26]:
info[['Subject ID','MSKCC type']].groupby('MSKCC type').count()

                            Subject ID
MSKCC type
Extraskeletal bone sarcoma           4
Fibrosarcoma                         1
Leiomyosarcoma                      10
Liposarcoma                         11
MFH                                 17
Other                                3
Synovial sarcoma                     5

In [64]:
meta_extracted = metadata[['Subject ID','Modality','Number of Images']]
info_extracted = info[['Subject ID','MSKCC type']]

In [67]:
# join two dataframes
meta_info_join = pd.merge(meta_extracted, info_extracted, on='Subject ID', how='inner')

In [68]:
meta_info_join

    Subject ID  Modality  Number of Images        MSKCC type
0      STS_001  RTSTRUCT                 1       Liposarcoma
1      STS_001        MR                40       Liposarcoma
2      STS_001  RTSTRUCT                 1       Liposarcoma
3      STS_001        MR                40       Liposarcoma
4      STS_001  RTSTRUCT                 1       Liposarcoma
..         ...       ...               ...               ...
607    STS_051  RTSTRUCT                 1  Synovial sarcoma
608    STS_051        CT               267  Synovial sarcoma
609    STS_051        MR                50  Synovial sarcoma
610    STS_051        MR                52  Synovial sarcoma
611    STS_051        PT               267  Synovial sarcoma

[612 rows x 4 columns]

In [79]:
(meta_info_join[['Modality', 'MSKCC type', 'Number of Images']]
 .groupby(['Modality', 'MSKCC type'])
 .sum()
 .drop('RTSTRUCT', axis=0))

                                     Number of Images
Modality MSKCC type
CT       Extraskeletal bone sarcoma              1024
         Fibrosarcoma                             267
         Leiomyosarcoma                          2582
         Liposarcoma                             3069
         MFH                                     4583
         Other                                    801
         Synovial sarcoma                        1281
MR       Extraskeletal bone sarcoma               854
         Fibrosarcoma                             233
         Leiomyosarcoma                          1981
         Liposarcoma                             2355
         MFH                                     3862
         Other                                    567
         Synovial sarcoma                         901
PT       Extraskeletal bone sarcoma              1024
         Fibrosarcoma                             267
         Leiomyosarcoma                          2582
         Liposarcoma                             3069
         MFH                                     4583
         Other                                    801
         Synovial sarcoma                        1291